server:
  port: 8080
  servlet:
    session:
      timeout: 1m

logging:
  level:
    org.springframework.security: DEBUG

spring:
  application:
    name: security-demo
  mvc:
    #    servlet:
    #      path: /foo
    static-path-pattern: /**
  web:
    resources:
      static-locations:
        - "classpath:/META-INF/resources/"
        - "classpath:/resources/"
        - "classpath:/static/"
        - "classpath:/public/"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_demo?useUnicode=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: evan
    password: evan@1234
    #    initialization-mode: NEVER
    hikari:
      # 连接超时：3s
      connection-timeout: 30000
      # 校验超时：3s
      validation-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 10
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #        hbm2ddl:
        #          auto: update
        dialect: org.hibernate.dialect.MySQLDialect

